### ISSUE TITLE
如何烧录固件

### ISSUE THREAD

**Issue by sjz123321** [xxp1943/HanshowEpd#1]
你好，我手头上只有JLINK我想请教一下是否可以使用JTAG接口烧录或者仿真芯片，谢谢！

**Comment by reiyawea** [comment]
MSP430系列只支持自家专用的调试器。
一般来说ARM系列会配备JTAG接口，大多8位MCU都是自家专用调试接口。
你可以去买一个TI launchpad，可以借用板载调试器。
